### ISSUE TITLE
Support proguard 7.3.0+

### ISSUE THREAD

**Issue by onacit** [wvengen/proguard-maven-plugin#300]
It seems the plugin doesn't work with produgard 7.3.0+.

```
 [proguard] Exception in thread "main" java.lang.NoSuchMethodError: 'void proguard.io.ClassReader.<init>(boolean, boolean, boolean, boolean, boolean, proguard.classfile.util.WarningPrinter, proguard.classfile.visitor.ClassVisitor)'
 [proguard]     at proguard.InputReader.execute(InputReader.java:93)
 [proguard]     at proguard.pass.PassRunner.run(PassRunner.java:24)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:327)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:118)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:645)
 [proguard] ProGuard, version 7.3.0
```

```
 [proguard] Exception in thread "main" java.lang.NoSuchMethodError: 'void proguard.io.ClassReader.<init>(boolean, boolean, boolean, boolean, boolean, proguard.classfile.util.WarningPrinter, proguard.classfile.visitor.ClassVisitor)'
 [proguard]     at proguard.InputReader.execute(InputReader.java:93)
 [proguard]     at proguard.pass.PassRunner.run(PassRunner.java:24)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:333)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:124)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:651)
 [proguard] ProGuard, version 7.4.0
```

**Comment by shpatbraina** [comment]
@lasselindqvist can you please update ProGuard dependencies version to fix this issue. This will enable the option of using this plugin with JDK 21.
![image](https://github.com/wvengen/proguard-maven-plugin/assets/26443409/792b682f-9856-4217-9105-b62f7835edf2)

**Comment by onacit** [comment]
@shpatbraina Thank you for your help!

I'm not sure what's the difference between `proguard-base` and `proguard-core`.

It works now with  the `proguard-core`.

https://github.com/jinahya/proguard-with-maven-example/blob/develop/pom.xml
